# Generated by Django 3.0.6 on 2020-05-11 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CowSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_text', models.CharField(max_length=150)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
